### ISSUE TITLE
Clarity in the behaviour

### ISSUE THREAD

**Issue by pandeesh** [scribd/hive-udaf-maxrow#1]
Hi,

What will be the expected behavior of maxrow(), when the key value is duplicated.?
So, in your example , if i add one more record like.
1   4   data-1,5
What will be the result for SELECT id, maxrow(ts, somedata) FROM sometable GROUP BY id;?
whether it's  1     4   data-1,5 or 1   4   data-1,4

Thanks,

**Comment by mbirk** [comment]
I would expect the result to be undefined.  That is, it could return either data-1,4 or data-1,5.  The actual result would depend on which record the UDAF processed first, and I don't think that Hive provides any guarantees about the ordering.

**Comment by pandeesh** [comment]
Cool, thanks for confirming
